apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: retail-app
type: Opaque
stringData:
  username: admin
  password: BedrockMySQL2025!
  host: project-bedrock-mysql.cofeq2eis5an.us-east-1.rds.amazonaws.com
  port: "3306"
  database: retailstore
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: retail-app
type: Opaque
stringData:
  username: postgres
  password: BedrockPG2025!
  host: project-bedrock-postgres.cofeq2eis5an.us-east-1.rds.amazonaws.com
  port: "5432"
  database: retailstore
